import "./globals.css";
import { lilitaOne } from "./fonts";
import { notoSans } from "./fonts";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={"h-full " + lilitaOne.className + notoSans.className}>{children}</body>
    </html>
  );
}
